### PR TITLE
vicon_sdk uses C++11 components

### PR DESCRIPTION
**Pull request by danmox**
I added C++11 flags to fix the vicon_sdk compilation error.

### CODE REVIEW

**Comment by versatran01** [comment]
Prefer 
```
set(CMAKE_CXX_STANDARD 11)
```
or 
```
set_target_properties(myTarget PROPERTIES
    CXX_STANDARD 11
)
```
Just my thoughts.

**Comment by danmox** [comment]
`CMAKE_CXX_STANDARD` / `CXX_STANDARD` are available in cmake 3.1+ but the minimum version is set at 2.8.12, hence the use of `add_compile_options`.

I'm happy to use a more modern approach if you see no issue with bumping the cmake minimum required version to 3.1+.

**Comment by mike-watterson-ai** [comment]
The only issue would be with anyone still on 14.04, but I believe most people have upgraded by now.

**Comment by tdinesh** [comment]
There are some people still on 14.04. Also, the Fetch robot is also still at 14.04. Can you create a branch devel_indigo and then merge this in master? @mdkennedy3

**Comment by kartikmohta** [comment]
The whole package uses C++11 which was enabled in the main CMakeLists.txt, just that it was done after including the `vicon_sdk` subdirectory. I just pushed bbc1245c6241a523d374da5ebff0df97c1ea10c4 which I think is the simplest fix to this particular issue but we should "modernize" it at some point (probably after 14.04 is EOL).

**Comment by kartikmohta** [comment]
@danmox I'll delete the `indigo-devel` branch and close this PR for now. I created a separate issue (#12) for updating the cmake syntax when we don't need to support Ubuntu 14.04.

**Pull request closed without merging**
